[tui]
payload.color_theme = "apathy"  # color theme for the payload tab, default is "solarized-dark"

[runner]
# capture_http = true     # capture HTTP debug logs, default is false
# capture_rust = true     # capture Rust "log" crate logs, default is false
# show_sensitive = true   # show sensitive data in HTTP logs instead of masking, default is false
# concurrency = 4         # max parallel tests, default is unlimited (test mode) or CPU cores (tui mode)

[[projects]]
name = "default"        # project name
test_ignore = []        # list of test names to exclude
retry.count = 0         # retry count, default is 0
retry.factor = 2.0      # factor for backoff, default is 2.0
retry.jitter = false    # true to enable backoff jitter, default is false
retry.min_delay = "1s"  # minimum delay for backoff, default is 1s
retry.max_delay = "60s" # maximum delay for backoff, default is 60s
